# Generated by Django 2.2.6 on 2019-12-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pwd',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='密文密码'),
        ),
    ]
